---
all:
  hosts:
  vars:
  children:
    scripts:
      hosts:
        192.168.16.36
      vars:
        ansible_user: dudu
        ansible_password: dudu
        ansible_become_password: dudu
    kubernetes:
      hosts:
      vars:
        ansible_user: duDoong
        ansible_password: duDoong
        ansible_become_password: duDoong
      children:
        master:
          hosts:
            192.168.16.40
        worker1:
          hosts:
            192.168.16.41
        worker2:
          hosts:
            192.168.16.42
...