---
- name: Copy scripts.tar.gz to Remote Server
  ansible.builtin.copy:
    src: /home/ansible/192.168.16.36/home/dudu/scripts.tar.gz
    dest: /tmp/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  tags:
  - copy

- name: Extract scripts.tar.gz file
  command: tar -zxvf scripts.tar.gz scripts/ chdir=/tmp/
  args:
    warn: false
  register: extract

- name: Run Podman Scripts
  command: /bin/bash run.sh chdir=/tmp/scripts/podman
  register: run

- name: Fetch Result File
  ansible.builtin.fetch:
    src: /tmp/scripts/podman/stdout.txt
    dest: /home/ansible/ansible-playbook/diagnose/result
  when: result_file.stat.exists

- name: Fetch Verbose File
  ansible.builtin.fetch:
    src: /tmp/scripts/podman/verbose
    dest: /home/ansible/ansible-playbook/diagnose/result
  when: verbose_file.stat.exists
...